language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - export TAG=v$TRAVIS_BUILD_NUMBER
  - docker tag udagram-api-feed thantnaylin/udagram-api-feed:$TAG
  - docker tag udagram-api-user thantnaylin/udagram-api-user:$TAG
  - docker tag udagram-frontend thantnaylin/udagram-frontend:$TAG
  - docker tag udagram-reverseproxy thantnaylin/udagram-reverseproxy:$TAG

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push thantnaylin/udagram-api-feed:$TAG
  - docker push thantnaylin/udagram-api-user:$TAG
  - docker push thantnaylin/udagram-frontend:$TAG
  - docker push thantnaylin/udagram-reverseproxy:$TAG